update github action

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -14,19 +14,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Search
+      - name: Checking coding style
         run: |
-          find / -type f -name "coding-style"
-
-#      - name: Checking coding style
-#        run: |
-#          FILES=$(find . -type f \( -name "*.c" -o -name "*.h" \))
-#          epiclang $FILES -I $(find . -type f -name "*.h" -exec dirname {} \;)
-#          echo $?
-#          if [ $? -ne 0 ]; then
-#            echo "::error::Coding style errors detected."
-#            exit 84
-#          fi
+          FILES=$(find . -type f \( -name "*.c" -o -name "*.h" \))
+          ret=epiclang $FILES -I $(find . -type f -name "*.h" -exec dirname {} \;)
+          echo ret
+          if [ ret -ne 0 ]; then
+            echo "::error::Coding style errors detected."
+            exit 84
+          fi
 
       - name: Build Project
         run: |
