update github action

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -9,20 +9,22 @@ jobs:
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
-        
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
-      - name: Run Coding Style Check
-        run: |
-          find . -type f -name "*.c";
-          find . -type f -name "*.h"
 
       - name: Build Project
         run: |
           make
           if [ ! -f ./my_world ]; then
             echo "::error::Binary 'my_world' not found."
+            exit 1
+          fi
+
+          echo "Checking coding style..."
+          find ./src -name '*.c' -o -name '*.h' | xargs epicheck
+          if [ $? -ne 0 ]; then
+            echo "::error::Coding style errors detected."
             exit 1
           fi
