update github action

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -10,20 +10,26 @@ jobs:
     container:
       image: epitechcontent/epitest-docker:latest
     
-    env:
-      CC: epiclang
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Build Project
+      - name: Build Project and Check Coding Style
         timeout-minutes: 2
         run: |
           make
+
           if [ ! -f ./my_tests ]; then
             echo "❌ Error: Binary 'my_tests' not found. Check your Makefile."
-            ls -R # Aide au debug pour voir ce qui a été généré
+            ls -R
+            exit 1
+          fi
+
+          echo "🔎 Checking coding style..."
+          find . -type f -name "*.c" -exec epiclang {} +
+
+          if [ $? -ne 0 ]; then
+            echo "❌ Coding style errors detected."
             exit 1
           fi
       
