update github action

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -15,12 +15,12 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Build Project
-              run: |
-                make
-                if [ ! -f ./my_tests ]; then
-                  echo "::error::Binary 'my_tests' not found."
-                  exit 1
-                fi
+        run: |
+          make
+          if [ ! -f ./my_tests ]; then
+            echo "::error::Binary 'my_tests' not found."
+            exit 1
+          fi
 
       - name: Check Coding Style
         run: |
